Repository vapor/fluent-sqlite-driver, pull requests merged in 2020-05, with the labels that each got.

#56 Make tests respect the LOG_LEVEL env var
  Tests/FluentSQLiteDriverTests/FluentSQLiteDriverTests.swift
Labels: enhancement

#55 Configure SQLiteConnectionSource with Database ID
  .github/workflows/test.yml
  Package.swift
  Tests/FluentSQLiteDriverTests/FluentSQLiteDriverTests.swift
Labels: bug, semver-patch

#57 FluentKit 1.0.0 GM
  Package.swift
  Sources/FluentSQLiteDriver/FluentSQLiteDatabase.swift
  Sources/FluentSQLiteDriver/FluentSQLiteDriver.swift
  Sources/FluentSQLiteDriver/SQLiteConverterDelegate.swift
  Sources/FluentSQLiteDriver/SQLiteRow+Database.swift
  Tests/FluentSQLiteDriverTests/FluentSQLiteDriverTests.swift
Labels: enhancement, semver-major

#60 Make the tests run with more threads
  Tests/FluentSQLiteDriverTests/FluentSQLiteDriverTests.swift
Labels: enhancement
